#ifndef EEZ_LVGL_UI_VARS_H
#define EEZ_LVGL_UI_VARS_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// enum declarations



// Flow global variables

enum FlowGlobalVariables {
    FLOW_GLOBAL_VARIABLE_LOADING_VALUE = 0,
    FLOW_GLOBAL_VARIABLE_KEYS = 1,
    FLOW_GLOBAL_VARIABLE_EYE_OPEN = 2,
    FLOW_GLOBAL_VARIABLE_BATTERY_LEVEL = 3,
    FLOW_GLOBAL_VARIABLE_DOSIS_PUNTUAL = 4,
    FLOW_GLOBAL_VARIABLE_DOSIS_TOTAL = 5,
    FLOW_GLOBAL_VARIABLE_IDIOMA = 6,
    FLOW_GLOBAL_VARIABLE_WIFI_NAME = 7,
    FLOW_GLOBAL_VARIABLE_CONNECTION_STATE = 8,
    FLOW_GLOBAL_VARIABLE_WIFI_ON = 9,
    FLOW_GLOBAL_VARIABLE_BUTTON_MATRIX_VISIBLE = 10,
    FLOW_GLOBAL_VARIABLE_ACTIVE_FIELD = 11,
    FLOW_GLOBAL_VARIABLE_PASS_CURRENT = 12,
    FLOW_GLOBAL_VARIABLE_PASS_NEW = 13,
    FLOW_GLOBAL_VARIABLE_PASS_CONFIRM = 14,
    FLOW_GLOBAL_VARIABLE_PIN_INCORRECTO = 15,
    FLOW_GLOBAL_VARIABLE_STORED_PASSWORD = 16,
    FLOW_GLOBAL_VARIABLE_NOTIFICATION_TEXT = 17,
    FLOW_GLOBAL_VARIABLE_SHOW_NOTIFICATION = 18,
    FLOW_GLOBAL_VARIABLE_CHECK_R = 19,
    FLOW_GLOBAL_VARIABLE_CHECK_V = 20,
    FLOW_GLOBAL_VARIABLE_CHECK_IR = 21,
    FLOW_GLOBAL_VARIABLE_TREATMENT_TIME = 22,
    FLOW_GLOBAL_VARIABLE_DOSIS_P_C = 23,
    FLOW_GLOBAL_VARIABLE_DOSIS_T_C = 24,
    FLOW_GLOBAL_VARIABLE_IS_RUNNING = 25
};

// Native global variables

extern const char *get_var_output_keyboard();
extern void set_var_output_keyboard(const char *value);


#ifdef __cplusplus
}
#endif

#endif /*EEZ_LVGL_UI_VARS_H*/